spring.application.name=intergalactic-market

feature.toggles.cosmoCats=true
feature.toggles.kittyProducts=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dependencies.manager_factory_delegate=true
spring.jpa.properties.hibernate.dependencies.manager_factory_delegate.dependsOn=liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
