spring.application.name=intergalactic-market

feature.toggles.cosmoCats=true
feature.toggles.kittyProducts=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
